# Generated by Django 4.2.7 on 2023-11-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('url', models.CharField(max_length=100, verbose_name='URL')),
                ('imagen', models.ImageField(upload_to='slider_images/')),
            ],
        ),
    ]
