# Generated by Django 4.2.7 on 2023-11-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='nombre',
        ),
        migrations.AddField(
            model_name='slider',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
