# Generated by Django 4.2.7 on 2023-11-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_remove_slider_nombre_slider_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='nombre',
            field=models.CharField(default='Alcoba Gris', max_length=45, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
