# Generated by Django 4.2.7 on 2024-02-17 11:13

from django.db import migrations, models
import operaciones.models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='operaciones\\productos\\default-product.png', null=True, upload_to=operaciones.models.get_image_filename),
        ),
    ]
