# Generated by Django 5.0.3 on 2024-03-28 00:24

import operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, default='operaciones\\fotos\\default-foto.png', null=True, upload_to=operaciones.models.get_image_filename)),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
