# Generated by Django 5.0.3 on 2024-03-28 14:36

import operaciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='estado',
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.ImageField(blank=True, default='operaciones\\fotos\\default-Product.png', null=True, upload_to=operaciones.models.get_image_filename),
        ),
    ]
