# Generated by Django 5.0.3 on 2024-03-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_foto_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='tienda',
        ),
        migrations.AddField(
            model_name='foto',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
