# Generated by Django 5.0.3 on 2024-03-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0031_delete_galeria'),
        ('operaciones', '0006_remove_foto_tienda_foto_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='tienda',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comunidad.tienda', verbose_name='Tienda'),
            preserve_default=False,
        ),
    ]
