# Generated by Django 5.0.3 on 2024-03-28 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_foto_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='tienda',
        ),
    ]
