# Generated by Django 5.0.3 on 2024-03-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_alter_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='tienda',
        ),
    ]
