# Generated by Django 5.0.3 on 2024-04-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0017_cita'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cita',
        ),
    ]
