# Generated by Django 4.2.7 on 2024-02-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0004_rename_primerprimer_nombre_usuario_primer_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('nit', models.PositiveIntegerField(unique=True, verbose_name='NIT')),
                ('estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comunidad.usuario', verbose_name='Administrador')),
            ],
        ),
    ]
