# Generated by Django 4.2.7 on 2024-02-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0014_usuario_rol_alter_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='usuario',
        ),
    ]
