# Generated by Django 4.2.7 on 2024-02-14 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0017_remove_tienda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='usuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='comunidad.usuario', verbose_name='Administrador'),
            preserve_default=False,
        ),
    ]
