# Generated by Django 4.2.7 on 2024-02-15 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0018_tienda_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='usuario',
        ),
    ]
