# Generated by Django 4.2.7 on 2024-02-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0023_alter_tienda_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
