# Generated by Django 4.2.7 on 2024-02-15 13:11

import comunidad.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0024_alter_tienda_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, default='comunidad\\default-user.jpeg', null=True, upload_to=comunidad.models.get_image_filename),
        ),
    ]
