# Generated by Django 4.2.7 on 2024-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0025_remove_usuario_rol_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('AD', 'Administrador'), ('CL', 'Cliente'), ('TE', 'Tendero')], default='CL', max_length=2, verbose_name='Rol'),
        ),
    ]
