# Generated by Django 4.2.7 on 2024-02-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0027_remove_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('AD', 'Administrador'), ('CL', 'Cliente'), ('TE', 'Tendero')], default='CL', max_length=2, verbose_name='Rol'),
        ),
    ]
