# Generated by Django 4.2.7 on 2024-02-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0028_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
