# Generated by Django 4.2.7 on 2024-02-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunidad', '0030_galeria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galeria',
        ),
    ]
